name: cargo-cache
description: Cache cargo dependencies

inputs:
  workdir:
    default: '.'

runs:
  using: composite
  steps:
    # https://github.com/actions/cache/blob/v3/examples.md#rust---cargo
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ${{ inputs.workdir }}/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
